
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 02 20:54:27 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 19;
  public static final int MENOS = 7;
  public static final int OR = 20;
  public static final int IGUAL = 13;
  public static final int DECIMAL = 4;
  public static final int MAYIGUAL = 17;
  public static final int NOT = 21;
  public static final int UMENOS = 5;
  public static final int POT = 10;
  public static final int ID = 2;
  public static final int MEN = 16;
  public static final int MENIGUAL = 18;
  public static final int EOF = 0;
  public static final int MULT = 8;
  public static final int DIV = 9;
  public static final int PAR_IZQ = 11;
  public static final int error = 1;
  public static final int PAR_DER = 12;
  public static final int MAY = 15;
  public static final int ENTERO = 3;
  public static final int MAS = 6;
  public static final int DIF = 14;
}

